---
title: "What Moves the City? How COVID, Events and Weather Shaped Sydney’s Train Usage (2020–2025)"
author: "Nihira Sharma(530784106), Paakhi Dodwani(SID), Pranav Lokhande(SID)"
date: "2025-07-22"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_section: true
    code_folding: hide
    theme: united
    highlight: tango
---

# Import Libraries

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggiraph)
  library(sf)
  library(rnaturalearth)
  library(rnaturalearthdata)
})
```

# Exetutive Summary
[TODO]

# Introduction
[TODO]

# COVID TOpic

[TOOD]

- Show Opal data from 2020–2021 during lockdowns.
- Focus on CBD stations (e.g., Town Hall, Wynyard).
- Compare pre-COVID peaks vs lockdown silence.
Message: When fear and policy collide, the city shuts down.

# Vivid and Christmas

[TODO]

- Analyze spikes in evening entries during Vivid (May–June) and NYE (Dec 31).
- Use Circular Quay, Martin Place, and Town Hall as focal points.
- Compare normal weeks vs event weeks.
Message: Events light up the city — literally and in the data.

# Weather

[TOOD]

- Use BOM + Opal to track rainy weeks (e.g. March 2022 floods).
- Show daily entries dipping during heavy rainfall.
- Contrast with COVID and event peaks.
Message: Rain doesn’t cancel life — but it delays it.

# Comparative View: Which Force Disrupted the Most?

[TODO]

Create visual side-by-side comparisons:
- % drop during COVID, during storms, and non-holiday baseline
- % spike during events like Vivid
- Show recovery speed — e.g. rain recovers in a day, COVID takes months
- Possibly create a “disruption index” to quantify impact level and duration.

# Conclusion: Moving Forward, Mindfully

[TODO]

- Reflect on what each disruption teaches:
- COVID = city shutdown, long recovery
- Events = fast joy, short-term crowding
- Weather = persistent but brief friction
Call to action: Design smarter transit plans that adapt to multiple disruption types not just one.



 
 
 

